// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimeSearchController from "./anime_search_controller"
application.register("anime-search", AnimeSearchController)

import AutoCompleteController from "./auto_complete_controller"
application.register("auto-complete", AutoCompleteController)

import GenreModalController from "./genre_modal_controller"
application.register("genre-modal", GenreModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import SearchClearController from "./search_clear_controller"
application.register("search-clear", SearchClearController)

import SeichiSearchController from "./seichi_search_controller"
application.register("seichi-search", SeichiSearchController)

import StepFormController from "./step_form_controller"
application.register("step-form", StepFormController)
